EnableSnortMonitoring=off
EnableSSHMonitoring=on
EnableHTTPMonitoring=off
LogFacility=file
LogLevel=info
BlockCount=3
FirewallAction=DROP
IgnoreFile=/var/ipfire/guardian/ignored
LogFile=/var/log/guardian/guardian.log
SocketOwner=nobody:nobody
FirewallEngine=IPtables
