deny bootp;	#default
authoritative;
ddns-update-style none;

subnet 192.168.1.0 netmask 255.255.255.0 #GREEN
{
pool {
	range 192.168.1.100 192.168.1.200;
     }
	option subnet-mask 255.255.255.0;
	option domain-name "localdomain";
	option routers 192.168.1.1;
	option domain-name-servers 192.168.1.1;
	option ntp-servers 192.168.1.1;
	default-lease-time 3600;
	max-lease-time 7200;
} #GREEN

on commit {
	set ClientAddress = concat(
		"ADDRESS=",
		binary-to-ascii(10, 8, ".", leased-address)
	);
	set ClientName = concat(
		"NAME=",
		pick-first-value(option host-name, config-option-host-name, client-name, "")
	);

	if (ClientName != "") {
		execute("/usr/sbin/unbound-dhcp-leases-client", "commit", ClientAddress, ClientName);
	}
}

on release {
	set ClientAddress = concat(
		"ADDRESS=",
		binary-to-ascii(10, 8, ".", leased-address)
	);
	set ClientName = concat(
		"NAME=",
		pick-first-value(option host-name, config-option-host-name, client-name, "")
	);

	if (ClientName != "") {
		execute("/usr/sbin/unbound-dhcp-leases-client", "release", ClientAddress, ClientName);
	}
}

on expiry {
	set ClientAddress = concat(
		"ADDRESS=",
		binary-to-ascii(10, 8, ".", leased-address)
	);

	execute("/usr/sbin/unbound-dhcp-leases-client", "expiry", ClientAddress);
}

include "/var/ipfire/dhcp/dhcpd.conf.local";
