# Forward all received syslog to Malcolm Filebeat syslog listener
*.* action(type="omfwd"
           target="127.0.0.1"
           port="5514"
           protocol="udp"
           action.resumeRetryCount="3"
           queue.type="LinkedList"
           queue.size="10000")
