#!/bin/bash
# check-drift.sh — Full manifest drift detection
# Deploy to: /root/firewall-repo/scripts/check-drift.sh on IPFire
# Usage:
#   bash check-drift.sh                  Verify live files against manifest (default)
#   bash check-drift.sh --generate       Generate manifest from live files (run after deploy)
#
# Exit codes: 0=no drift, 1=error (missing manifest), 2=drift detected
#
# Distinction from check-integrity.sh (per D-15):
#   check-integrity.sh — 8 critical files, baseline stored ON IPFire, monitors for Core Update overwrites
#   check-drift.sh    — ALL managed files, manifest stored IN REPO, detects any deviation from known-good state

MANIFEST="/root/firewall-repo/manifests/file-manifest.sha256"

# Full list of files managed by this repo
# Note: WUI-managed files are EXCLUDED — they change via WUI and would cause constant false-positive drift (per D-21)
MANAGED_FILES=(
  # Phase 1: Platform Foundation
  /etc/udev/rules.d/30-persistent-network.rules
  /etc/sysconfig/firewall.local
  /var/ipfire/backup/include.user
  # Phase 2: Core Network Services (repo-deployed configs only)
  /var/ipfire/dhcp/dhcpd.conf.local
  /etc/unbound/forward.conf
  # Phase 3: SSH (reference only — sshctrl manages live file)
  /etc/ssh/sshd_config
  # Phase 4: Suricata IDS/IPS
  /etc/suricata/suricata.yaml
  # Phase 5: Telemetry
  /etc/syslog.conf
  # Phase 6: System Hardening
  /etc/sysctl.conf
  # Integrity baseline (Phase 6)
  /root/integrity-baseline.sha256
  # Pakfire manifest (Phase 6)
  /root/firewall-repo/manifests/pakfire-manifest.txt
)

PASS=0
FAIL=0
WARN=0
CHANGED=0
MISSING=0

pass() { echo "OK: $1"; PASS=$((PASS + 1)); }
fail() { echo "FAIL: $1"; FAIL=$((FAIL + 1)); }
warn() { echo "WARN: $1"; WARN=$((WARN + 1)); }

MODE="${1:---verify}"

echo "=== File Manifest Drift Check === $(date)"
echo "Manifest: $MANIFEST"
echo "Mode: $MODE"
echo ""

# ------------------------------------------------------------------
# --generate mode: hash all managed files and write manifest
# ------------------------------------------------------------------
if [ "$MODE" = "--generate" ]; then
  echo "INFO: Generating manifest from live files..."
  echo "INFO: Writing to $MANIFEST"
  echo ""

  # Write header
  cat > "$MANIFEST" <<'HEADER'
# file-manifest.sha256 — Full managed file manifest
# Generated by: bash check-drift.sh --generate (run ON IPFire)
# WARNING: Always generate on IPFire — CRLF differences on dev machine will cause false mismatches.
# Do NOT hash files on the dev machine.
HEADER

  BASELINED=0
  SKIPPED=0

  for FILE in "${MANAGED_FILES[@]}"; do
    if [ ! -f "$FILE" ]; then
      warn "File not found — skipping from manifest: $FILE"
      SKIPPED=$((SKIPPED + 1))
    else
      sha256sum "$FILE" >> "$MANIFEST"
      pass "Baselined: $FILE"
      BASELINED=$((BASELINED + 1))
    fi
  done

  echo ""
  echo "INFO: Manifest written to $MANIFEST"
  echo "      Results: ${BASELINED} files baselined, ${SKIPPED} files skipped (not found)"

  if [ "$SKIPPED" -gt 0 ]; then
    echo "WARN: Some files were missing — re-run --generate after deploying all configs"
  fi

  exit 0
fi

# ------------------------------------------------------------------
# verify mode (default): compare live files against manifest
# ------------------------------------------------------------------
if [ ! -f "$MANIFEST" ]; then
  echo "FAIL: Manifest not found at $MANIFEST"
  echo "      Run: bash check-drift.sh --generate (on IPFire after deployment)"
  exit 1
fi

echo "INFO: Verifying live files against manifest..."
echo ""

while IFS= read -r LINE; do
  # Skip comment lines and blank lines
  [[ "$LINE" =~ ^# ]] && continue
  [[ -z "$LINE" ]] && continue

  # Parse: sha256sum format is "hash  filepath" (two spaces)
  EXPECTED_HASH=$(echo "$LINE" | awk '{print $1}')
  FILE_PATH=$(echo "$LINE" | awk '{print $2}')

  if [ -z "$FILE_PATH" ]; then
    warn "Malformed manifest line — skipping: $LINE"
    continue
  fi

  if [ ! -f "$FILE_PATH" ]; then
    echo "MISSING: $FILE_PATH"
    MISSING=$((MISSING + 1))
    continue
  fi

  ACTUAL_HASH=$(sha256sum "$FILE_PATH" 2>/dev/null | awk '{print $1}')

  if [ "$ACTUAL_HASH" = "$EXPECTED_HASH" ]; then
    pass "$FILE_PATH"
  else
    echo "CHANGED: $FILE_PATH"
    echo "         Expected: $EXPECTED_HASH"
    echo "         Actual:   $ACTUAL_HASH"
    CHANGED=$((CHANGED + 1))
  fi

done < "$MANIFEST"

echo ""
echo "=== Drift check complete === Results: ${PASS} ok, ${CHANGED} changed, ${MISSING} missing"

if [ "$CHANGED" -gt 0 ] || [ "$MISSING" -gt 0 ]; then
  echo "WARN: Drift detected — review changed/missing files above"
  echo "      After restoring configs, regenerate manifest:"
  echo "        bash check-drift.sh --generate"
  exit 2
fi

exit 0
